Switch to python3.8 for awx-ee
ansible/awx-ee pull request #18
Opened 2020-12-17 19:10 UTC by pabelanger

This rebuilds the awx-ee container image, using python3.8 as the base
version of python.

Depends-On: https://github.com/ansible/awx-ee/pull/17
Depends-On: https://github.com/ansible/ansible-runner/pull/594
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

2020-12-17 19:14 UTC, pabelanger commented
Pull-request updated, HEAD is now e650a5df4ae528619bed1e964e7296c906489d17

2020-12-17 19:15 UTC, pabelanger commented
Pull-request updated, HEAD is now 708f676c1914f8e019572697210e54e1a8d0f9d8

2020-12-17 19:16 UTC, pabelanger commented
recheck

2020-12-17 19:23 UTC, AlanCoding approved these changes
verified that it's building locally

2020-12-17 19:26 UTC, shanemcd commented
I dont think we should merge this until we have answers for: https://github.com/ansible/ansible-runner/pull/594#issuecomment-747647955

2020-12-17 19:28 UTC, pabelanger commented
Agree, 

> I dont think we should merge this until we have answers for: [ansible/ansible-runner#594 (comment)](https://github.com/ansible/ansible-runner/pull/594#issuecomment-747647955)

Agree, also zuul won't merge even if gate label is applied, until all depends-on are merged.

2020-12-17 19:37 UTC, shanemcd requested changes
A more formal -1: I would like to hold off on this until we have answers for: https://github.com/ansible/ansible-runner/pull/594#issuecomment-747647955

2020-12-18 15:25 UTC, shanemcd approved these changes
After discussion yesterday we have decided to #shipit.

2020-12-18 18:23 UTC, pabelanger commented
recheck

2020-12-18 18:24 UTC, pabelanger commented
This failed due to race condition publishing new ansible-runner py38 image. I plan to work on fixing this over shutdown.

2020-12-18 19:43 UTC, merged